### PR TITLE
Fix accumulation of latency and avgqu_sz from iostat

### PR DESCRIPTION
**Pull request by lippirk**
continuation of discussion: https://github.com/xenserver/rrdd-plugins/pull/61#discussion_r391094767

### CODE REVIEW

**Comment by edwintorok** [comment]
Yes for latency max is OK, for average queue size we may not have enough information to calculate it correctly.

**Comment by lippirk** [comment]
> Yes for latency max is OK, for average queue size we may not have enough information to calculate it correctly.

so you don't want to return NaN when we have more than one VDI? (that is, accumulating over a list with length > 1)

**Comment by edwintorok** [comment]
Lets merge this as is for now, I couldn't come up with a way that is less confusing and less incorrect than what we have now and in this PR. We should be measuring these values directly instead of inferring them, but that needs the counters to be available at the kernel level first (but that is not available for all device types).
Perhaps eBPF (already in 8.0) could help us here in the future because we could define our own counters inside the kernel more easily.

**Comment by olivierlambert** [comment]
Hi guys!

Just wanted to let you know: as it seems this fix is bundled in 8.2, we had reports on better values reported, but there's still something off.

See the feedback of our one user: https://xcp-ng.org/forum/post/31888

Feel free to post there if you like to ask questions, you can use your GitHub account :+1:

**Pull request merged**
